# Generated by Django 5.2.4 on 2025-09-17 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('locality', models.CharField(max_length=200, verbose_name='Bairro/Localidade')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('mobile', models.CharField(help_text='Inclua o indicativo (+258)', max_length=15, verbose_name='Telemóvel')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('state', models.CharField(choices=[('Cabo Delgado', 'Cabo Delgado'), ('Niassa', 'Niassa'), ('Nampula', 'Nampula'), ('Zambézia', 'Zambézia'), ('Tete', 'Tete'), ('Sofala', 'Sofala'), ('Manica', 'Manica'), ('Inhambane', 'Inhambane'), ('Gaza', 'Gaza'), ('Maputo Província', 'Maputo Província'), ('Maputo Cidade', 'Maputo Cidade')], max_length=50, verbose_name='Província')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
