# Generated by Django 5.2.4 on 2025-09-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteoro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodapp',
            new_name='description',
        ),
    ]
