# Generated by Django 5.2.4 on 2025-09-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteoro', '0002_rename_prodapp_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CL', 'Celulares & Acessórios'), ('EL', 'Eletrônicos'), ('ES', 'Esportes & Lazer'), ('IN', 'Informática'), ('AU', 'Áudio & Fones'), ('GA', 'Games & Consoles'), ('CA', 'Câmeras & Fotografia'), ('RE', 'Relógios & Smartwatches'), ('OF', 'Ofertas Especiais')], max_length=2),
        ),
    ]
