# Generated by Django 5.2.4 on 2025-09-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteoro', '0004_product_data_da_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-data_da_publicacao']},
        ),
    ]
