# Generated by Django 5.2.4 on 2025-10-02 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteoro', '0006_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Item do Carrinho', 'verbose_name_plural': 'Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-data_da_publicacao'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteoro.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CL', 'Celulares & Acessórios'), ('EL', 'Eletrônicos'), ('ES', 'Esportes & Lazer'), ('IN', 'Informática'), ('AU', 'Áudio & Fones'), ('GA', 'Games & Consoles'), ('CA', 'Câmeras & Fotografia'), ('RE', 'Relógios & Smartwatches'), ('OF', 'Ofertas Especiais')], max_length=2, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, default='', verbose_name='Composição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_da_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Promocional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Original'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
