# Generated by Django 5.2.4 on 2025-10-07 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteoro', '0007_alter_cart_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('province', models.CharField(max_length=100, verbose_name='Província')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade/Distrito')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('address', models.TextField(verbose_name='Endereço detalhado')),
                ('total', models.FloatField(verbose_name='Total do pedido')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('ENVIADO', 'Enviado'), ('CONCLUÍDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
