# Generated by Django 5.2.4 on 2025-10-30 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteoro', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meteoro.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteoro.product')),
            ],
        ),
    ]
