# Generated by Django 5.2.4 on 2025-10-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteoro', '0009_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
